### ISSUE TITLE
freeradius3 support in pkgsrc

### ISSUE THREAD

**Issue by coyhile** [TritonDataCenter/pkgsrc#18]
I had opened  joyent/pkgsrc-legacy#502 to update freeradius support to use FreeRADIUS 3.x and migrate pluggable backends to their own packages (mysql, pgsql, etc).

@mamash was massaging my initial work there before the Q2 code freeze. Just filing this so that that work doesn't get lost in the shuffle.

**Comment by mamash** [comment]
Coy, can you test the following patch? It's a wrap up of your work and my changes, made against current CVS trunk. I just don't have the opportunity to test the functionality, especially when it comes to the unfortunate config file management.

I've collected all the sub-packages under net/, it feels like a better fit since they are really just split-off files.

https://us-east.manta.joyent.com/filip/public/tmp/freeradius.patch

**Comment by coyhile** [comment]
I'll give it a shot, at least to the best of my ability. The extent of my testing is probably "does the server start in debug mode correctly. (I'm not an expert in FreeRADIUS by any means.) 

Out of curiosity (as I can't tell from the patch easily), how much different is this from what I tossed blindly over the wall?

**Comment by mamash** [comment]
Little bits really:

- PKGREVISION should be reset (removed) when updating to a new upstream version
- Easier to set INSTALLATION_DIRS+=lib once rather than pre-creating each time
- You can avoid examples/config file handling mess by setting something like INSTALL_MAKE_FLAGS+=raddbdir=${EGDIR}
- The Python module only supports Python 2.7 I think
- Some dependencies were missing for the rest module
- The dependency was not correct for the yubikey module

**Comment by mamash** [comment]
Running the daemon works, even the bundled test suite works. I was hoping you had a more real life setup ready to use this in... :)

**Comment by coyhile** [comment]
Ah, I see. And no, I haven't got a more real life setup yet. I got as far in my lab as "Let's get RADIUS setup. Oh wait, 3.x isn't in pkgsrc, so let's go down the rabbit hole instead of setting this up in a branded zone, no reason to use that."

**Comment by mamash** [comment]
I just committed the update to CVS.

**Comment by mamash** [comment]
Closing the issue, the update was committed. Unfortunately the binaries seem to reliably segfault right after start on NetBSD, but that's for another issue I guess.
