### ISSUE TITLE
pkgin install clang-9.0.1 killed pkgin itself

### ISSUE THREAD

**Issue by yb66** [TritonDataCenter/pkgsrc#241]
Hi there,

`pkgin install clang-9.0.1` led to:

```
$ pkgin help
dyld: Library not loaded: /opt/pkg/lib/libcrypto.1.0.0.dylib
  Referenced from: /opt/pkg/bin/pkgin
  Reason: image not found
[1]    1729 abort      pkgin help
```

It seems the first command updated libcrypto to v1.1 and pkgin was pointed at v1.0. It's fixed after a full reinstall, which was painful given I'd installed newer versions of curl and tar via pkgin too.

I think I've had this kind of thing happen once before. Is it not possible to lock versions of things that pkgin relies on, or perhaps it would be better to keep those things separate from the packages it manages?

Just a thought.

This was on a Mac, btw.

Regards,
iain

**Comment by jperkin** [comment]
There was a major OpenSSL 1.1.1 upgrade a few months ago, and unless all packages are upgraded at the same time to get past it then you can run into problems.

There was a bug in pkgin prior to this where a "pkgin install" would not consider all dependencies of a package, so in this case would not upgrade all packages affected by the OpenSSL upgrade.  This has since been fixed, but you would not have been running the fixed version of pkgin.

I'll be producing a newer macOS bootstrap so that new users don't hit this, and while I think I've now covered all of the install-related fixes, it's still worth always performing a "pkgin upgrade" prior to any "pkgin install" to ensure you have all the latest packages.

Thanks, and sorry for the breakage, it's hopefully a one-time thing.

**Comment by yb66** [comment]
@jperkin,

I see, that's fair enough. Thanks for taking the time with this, it's much appreciated.

Regards,
iain

**Comment by Pictor13** [comment]
@jperkin , do you have a recommended easy way to fix this?

Possibly without compromising the packages already installed with `pkgin`?

Or a full reinstall either of `pkgin` *and* all the packages is needed?
(and not sure I won't need to reinstall them all or they will be working)

**Comment by jperkin** [comment]
A `pkgin full-upgrade` should suffice.  The issue is if you try to
`pkgin install` something prior to getting past the OpenSSL upgrade.

**Comment by Pictor13** [comment]
Pardon me, I wasn't clear enough.
I'm talking about fixing `pkgin` itself, after getting the "Library not loaded: /opt/pkg/lib/libcrypto.1.0.0.dylib" error, because of upgrading openssl already, without being previously aware of the effects on the package manager.
I can't run any `pkgin <command>`.

**Comment by jperkin** [comment]
Ah ok. You should be able to get past this by running `pkg_add -U pkgin openssl libarchive`, then pkgin should work again for you to run `pkgin full-upgrade` to update everything else.

**Comment by Pictor13** [comment]
Oh, I was trying just `openssl` without `libarchive`; it's restored now, thank you!! =)

**Comment by jperkin** [comment]
Yeh the error can be a little confusing as the `libcrypto.1.0.0.dylib` library dependency is coming from libarchive indirectly rather than from pkgin directly.
