### ISSUE TITLE
Claws-mail - el7 package question

### ISSUE THREAD

**Issue by jakub-olczyk** [TritonDataCenter/pkgsrc#245]
Hi!

I don't know if this is the right place to ask, but I am wondering - were there any recent changes in the `pkgin` repository for Linux?

I couldn't find `claws-mail` package that I have been using from around mid 2019 for my CentOS 7 installation. I get that this is a free service that distributes binary packages for people to use freely and I am deeply grateful for that :pray:. However I was wandering if this was a planned drop of some of the software in the repository that I just missed?

If so, and there are no plans for distributing more desktop oriented packages, could you perhaps point me to correct place where I could find some information how to set my own repo for pkgin to use?

Thank you very much for your time & work! :bowing_man: 

Cheers!

**Comment by jakub-olczyk** [comment]
Hi!
Today I saw that claws-mail is back in the el7 repository. I don't know if this is the result of this ticket or just some sync issues. Anyway, thank you! I'll close this issue then.

Cheers!

**Comment by jperkin** [comment]
Ah good! The reason it was missing for a while was that it depended upon the gcc7 package which for a time was broken:

https://us-east.manta.joyent.com/pkgsrc/public/reports/Linux/el7/trunk/x86_64/20200311.2241/meta/report.html

The gcc7 issue was fixed a few days ago, but that coincided with the el7 build host being offline for a while, and so it only started building again last night:

https://us-east.manta.joyent.com/pkgsrc/public/reports/Linux/el7/trunk/x86_64/20200318.2145/meta/report.html

Generally the only reason software stops being available in this repository is because of the build failing, we always attempt to build and publish anything.  If something isn't available, then just head over to the <https://mail-index.netbsd.org/pkgsrc-bulk/> archive and find the most recent pkgsrc-el7-trunk-x86_64 build.

**Comment by jakub-olczyk** [comment]
Thanks a lot for the explanation, as well as for the links!

I'll be sure to check the mailing list archive now if anything happens.

cheers!
