### ISSUE TITLE
Canonicalization issue in OpenDKIM 2.10.3 in trunk

### ISSUE THREAD

**Issue by russhan** [TritonDataCenter/pkgsrc#247]
I believe I've hit a canonicalization issue with OpenDKIM 2.10.3 in trunk.

Bug and patch discussed in: https://sourceforge.net/p/opendkim/bugs/226/#bd34

In my case the Message-ID header contents after the colon are on a new line in the original email and after keeping temporary files and looking at the normalized headers I see a space after the colon with message-id: <something> while all the other headers don't have a space.

**Comment by russhan** [comment]
I've submitted to upstream pkgsrc

https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=55171

but nothing has happened there either.

**Comment by rhansen** [comment]
This bug was fixed upstream (https://github.com/trusteddomainproject/OpenDKIM/commit/a65442161a6e59de49b3db9091754174e363c392) over 5 years ago, but upstream has not made a stable release since then.

Debian has been using various 2.11.0 prerelease versions since Stretch (June 2017), so it should be safe to bump this package to 2.11.0-Beta2 (the latest tag).

**Comment by russhan** [comment]
It appears to me that this issue got resolved with https://github.com/joyent/pkgsrc/commit/81e324d51e6b24d910bae5ef183e7c20a4ad4864
