### ISSUE TITLE
nvi not available despite being on the repository

### ISSUE THREAD

**Issue by ghost** [TritonDataCenter/pkgsrc#311]
On macOS (Big Sur Intel/x86) nvi isn't listed when I search for it using ```pkgin search nvi```, but it's present on the pkgsrc repository: https://github.com/joyent/pkgsrc/tree/trunk/editors/nvi

**Comment by jperkin** [comment]
Yeh, unfortunately just because a package is in pkgsrc doesn't mean it's going to be available as a binary package, there are usually at least a thousand broken packages on most platforms depending on build issues in the third-party software.

The bulk build reports are posted to <https://mail-index.netbsd.org/pkgsrc-bulk/> where the latest build for that package set is <https://mail-index.netbsd.org/pkgsrc-bulk/2021/08/29/msg021294.html> and from there you can find the exact failure log for nvi here <https://us-east.manta.joyent.com/pkgsrc/public/reports/Darwin/11.0/trunk/x86_64/20210827.1043/nvi-1.81.6nb13/build.log>

Most build issues are not very complicated, and are a great way to get into pkgsrc and/or software development.  In this case it's likely that simply adding `.include "../../converters/libiconv/buildlink3.mk` to the nvi pkgsrc Makefile will fix the problem (ensuring that iconv is available in the build environment, linking correctly against `libiconv`, and avoiding the undefined symbols error).

**Comment by ghost** [comment]
If I make a patch, or if I want to submit a new package, should I send it here, to NetBSD's pkgsrc-wip, or both?

**Comment by jperkin** [comment]
For new packages you should get a wip account (http://pkgsrc.org/wip/) and push your submissions there so we can easily test and import.  For patches either here or https://github.com/netbsd/pkgsrc. Thanks!

**Comment by lispstudent** [comment]
Just as reference for other people looking, same issue for gitea: present in [www/gitea](https://github.com/joyent/pkgsrc/tree/trunk/www/gitea), but currently not as binary:

```
# pkgin -v
pkgin 21.7.0 (using SQLite 3.36.0)

# pkgin install www/gitea
www/gitea is not available in the repository
calculating dependencies...done.
nothing to do.
```

**Comment by jperkin** [comment]
Which repository is this for? Note that pkgin does not accept pkgsrc paths as install arguments, you specify the package name, so the command would be `pkgin install gitea`, not `pkgin install www/gitea`.

**Comment by lispstudent** [comment]
It is inside an OmniOS `pkgsrc` zone, `omnios-r151038`:

```
# uname -a
SunOS git 5.11 omnios-r151038-b3a82a213e i86pc i386 i86pc

# pkgin update
processing remote summary (https://pkgsrc.joyent.com/packages/SmartOS/trunk/x86_64/All)...
database for https://pkgsrc.joyent.com/packages/SmartOS/trunk/x86_64/All is up-to-date

# pkgin install gitea
gitea is not available in the repository
calculating dependencies...done.
nothing to do.
```

**Comment by jperkin** [comment]
Ok, looks like the ugprade to go 1.17 broke this, I'll try to fix it this week.

**Comment by lispstudent** [comment]
> Ok, looks like the ugprade to go 1.17 broke this, I'll try to fix it this week.

I can confirm it is fixed and well working on my side. I had already tested it last week, but forgot to mention it here. Thanks!

**Comment by jperkin** [comment]
nvi has been available for a while and is also now in our required packages list.
